//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfCrowd {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfCrowd.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MIME content-type was specified and the content-type could not be derived from the fileName extension..
        /// </summary>
        internal static string PdfCrowdClient_InvalidFileContentTypeArgument {
            get {
                return ResourceManager.GetString("PdfCrowdClient_InvalidFileContentTypeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fileName string provided was not a short file name (the name of a file without path information)..
        /// </summary>
        internal static string PdfCrowdClient_InvalidFileNameArgument {
            get {
                return ResourceManager.GetString("PdfCrowdClient_InvalidFileNameArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PdfCrowdOptions object provided is invalid or incomplete..
        /// </summary>
        internal static string PdfCrowdClient_InvalidPdfCrowdOptions {
            get {
                return ResourceManager.GetString("PdfCrowdClient_InvalidPdfCrowdOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response from GetRemainingTokens could not be parsed as an integer value. Raw string value is in the Exception.Details property..
        /// </summary>
        internal static string PdfCrowdErrorCode_CouldNotParseGetRemainingTokens {
            get {
                return ResourceManager.GetString("PdfCrowdErrorCode_CouldNotParseGetRemainingTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PdfCrowd service took more than 40 seconds to generate the PDF so the job was aborted..
        /// </summary>
        internal static string PdfCrowdErrorCode_PdfGenerationTimeout {
            get {
                return ResourceManager.GetString("PdfCrowdErrorCode_PdfGenerationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PdfCrowd service returned HTTP 503 indicating you have made too many requests in a small time period (i.e. you have been rate-limited)..
        /// </summary>
        internal static string PdfCrowdErrorCode_RateLimited {
            get {
                return ResourceManager.GetString("PdfCrowdErrorCode_RateLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This exception should never happen: the Execute() callback was not executed..
        /// </summary>
        internal static string PdfCrowdErrorCode_ResponseWasNotProcessed {
            get {
                return ResourceManager.GetString("PdfCrowdErrorCode_ResponseWasNotProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the uploaded data exceeded 20MiB and the server returned HTTP 413 &quot;Request entity too large&quot;..
        /// </summary>
        internal static string PdfCrowdErrorCode_SourceDataTooLarge {
            get {
                return ResourceManager.GetString("PdfCrowdErrorCode_SourceDataTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A WebException was raised by the internal HttpWebRequest which was unexpected and so unhandled. See the InnerException property for details..
        /// </summary>
        internal static string PdfCrowdErrorCode_UnhandledWebException {
            get {
                return ResourceManager.GetString("PdfCrowdErrorCode_UnhandledWebException", resourceCulture);
            }
        }
    }
}
